### ISSUE TITLE
similarity_matrix

### ISSUE THREAD

**Issue by hanyao8** [kosta777/parallel-genomeseq#16]
Kind of a small issue, but having the constructor instance and actual matrix both named "similarity_matrix" was a bit confusing when reading the code

![Screenshot from 2019-11-12 18-15-38](https://user-images.githubusercontent.com/17160827/68694815-2863ce80-057a-11ea-8a56-60b52f72550d.png)
![Screenshot from 2019-11-12 18-16-06](https://user-images.githubusercontent.com/17160827/68694816-28fc6500-057a-11ea-81fd-2fba63bc7d6c.png)

**Comment by huanglangwen** [comment]
I’ll fix that in my pr.
